#!/usr/bin/env python3

import sys

from codes import sender


def main():
    sender_port = sys.argv[1]
    receiver_port = sys.argv[2]
    init_rtt = sys.argv[3]
    max_window = sys.argv[4]
    file_path = sys.argv[5]

    sender.Sender(sender_port, receiver_port, int(init_rtt), int(max_window), file_path)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit(0)
